name: Daily Regression
on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 1-5'

jobs:
  Regression:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: test
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - run: npm install
      - run: npm run regression
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          EDX_API_BASE_URL: ${{ secrets.EDX_API_BASE_URL }}
          API_HTML_STATUS_CLASS_THRESHOLD: 399
          MINISTRY_OWNERSHIP_TEAM_ID: ${{ secrets.AT_MINISTRY_OWNERSHIP_TEAM_ID }}
          CONTACT_IDENTIFIER: ${{ secrets.AT_CONTACT_IDENTIFIER }}
          TOKEN_CLIENT_ID: ${{ secrets.AT_TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET: ${{ secrets.AT_TOKEN_CLIENT_SECRET }}
          TOKEN_ENDPOINT: ${{ secrets.SOAM_TOKEN_URL }}
          TEST_ADMIN_USERNAME: ${{ secrets.AT_EDX_ADMIN_USERNAME }}
          TEST_ADMIN_PASSWORD: ${{ secrets.AT_EDX_ADMIN_PASSWORD }}
          TEST_EDX_ACTIVATE_USER_USERNAME: ${{ secrets.AT_EDX_ACTIVATE_USER_USERNAME }}
          TEST_EDX_ACTIVATE_USER_PWD: ${{ secrets.AT_EDX_ACTIVATE_USER_PWD }}



